name: Run Crypto Tutorial
on:
  schedule:
    - cron: '45 05,17,19 * * *'
      
jobs:
  build:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install pandoc and pandoc citeproc
        run: |
          brew install pandoc
          brew install pandoc-citeproc
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-3-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-3-
      - name: Install Packages
        run: |-
          Rscript -e "install.packages('renv')"
          Rscript -e 'renv::consent(provided = TRUE)'
          Rscript -e "renv::restore()"
      - name: Render Book
        run: |-
          Rscript -e "Sys.setenv('pins_key' = '${{secrets.PAT_PINS}}', 'shrimpy_public' = '${{secrets.SHRIMPY_PUBLIC}}', 'shrimpy_private' = '${{secrets.SHRIMPY_PRIVATE}}', 'shrimpy_user' = '${{secrets.SHRIMPY_USER}}', 'shrimpy_account_id' = '${{secrets.SHRIMPY_ACCOUNT_ID}}', 'coinmarketcapr_key' = '${{secrets.COINMARKETCAPR}}')"
          Rscript -e "bookdown::render_book('index.Rmd', clean_envir = FALSE, envir = parent.frame())"
      - name: Snapshot renv to update lockfile
        run: |-
          Rscript -e "renv::snapshot()"
      - name: Commit and push files
        run: |
          git config --local user.email "ries9112@colorado.edu"
          git config --local user.name "ries9112"
          git add .
          git commit -m "Add html output from CI process" -a
          git push https://ries9112:${{secrets.GITHUB_TOKEN}}@github.com/ries9112/cryptocurrencyresearch-org.git HEAD:master --force
