name: Run Crypto Tutorial
on:
  schedule:
    - cron: '45 02,03,14 * * *'

jobs:
  build:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-3-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-3-
      - name: Install Packages
        run: |-
          Rscript -e "install.packages('renv')"
          Rscript -e 'renv::consent(provided = TRUE)'
          Rscript -e "renv::restore()"
          Rscript -e "install.packages("bookdown", dependencies = TRUE)"
      - name: Refresh book
        run: |
          pins_key <- "${{secrets.PAT_PINS}}"
          
          bookdown::render_book('index.Rmd', clean_envir = FALSE, clean = FALSE)
        shell: Rscript {0}
      - name: Snapshot renv to update lockfile
        run: |-
          Rscript -e "renv::snapshot()"
      - name: Commit and push files
        run: |
          git config --local user.email "ries9112@colorado.edu"
          git config --local user.name "ries9112"
          git add .
          git commit -m "Refresh entire book from CI automated process" -a
          git push https://ries9112:${{secrets.GITHUB_TOKEN}}@github.com/ries9112/cryptocurrencyresearch-org.git HEAD:master --force
